# Site settings
title: "Medlay"
subtitle: A New Hybrid Media Form
description: "Medlay is a new concept for crafting multimedia artefacts on the Web."
author: Andrea Buran
exclude: ['README.md']

#baseurl: http://ranbureand.github.io/medlay
baseurl: /medlay

timezone: Europe/Rome
encoding: utf8

collections:
  chapters:
    output: true
    name: "Banana"

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..3