# Site settings
title: "Medlay"
subtitle: A New Hybrid Media Form
description: Bibbidi Bobbidi Bu.
author: Andrea Buran
exclude: ['README.md']

#baseurl: http://ranbureand.github.io/medlay
baseurl: /medlay

timezone: Europe/Rome
encoding: utf8

collections:
  chapters:
    output: true

# Build settings
markdown: kramdown